"""Exports: LSIF (JSON-lines subset) for tooling interop, JSON dump,
and a generated ARCHITECTURE.md."""
import json
from .base import repo_root
from .store import connect

def export(root=None, fmt="json", out=None):
    root = root or repo_root(); con = connect(root)
    if fmt == "lsif":     data = _lsif(con)
    elif fmt == "markdown": data = _markdown(con, root)
    else:                 data = _json_dump(con)
    text = data if isinstance(data, str) else json.dumps(data, indent=2, default=str)
    if out:
        with open(out, "w") as f: f.write(text)
        return {"wrote": out, "bytes": len(text)}
    print(text)
    return {"bytes": len(text)}

def _json_dump(con):
    return {"protocol": "cip", "version": "1.0.0",
            "files": [dict(r) for r in con.execute("SELECT path, language, lines, hash FROM files")],
            "symbols": [dict(r) for r in con.execute(
                "SELECT id, name, kind, path, start_line, end_line, signature FROM symbols")],
            "edges": [dict(r) for r in con.execute("SELECT src, dst, kind FROM edges")],
            "summaries": [dict(r) for r in con.execute("SELECT id, kind, path, source FROM summaries")],
            "signals": [dict(r) for r in con.execute("SELECT id, kind, path, name, ts FROM signals")]}

def _lsif(con):
    lines, eid = [], [0]
    def nid():
        eid[0] += 1; return eid[0]
    lines.append(json.dumps({"id": nid(), "type": "vertex", "label": "metaData",
                             "version": "0.4.3", "positionInfo": {"line": 1, "character": 1}}))
    proj = nid()
    lines.append(json.dumps({"id": proj, "type": "vertex", "label": "project", "kind": "cip"}))
    docs = {}
    for f in con.execute("SELECT path, language FROM files"):
        did = nid(); docs[f["path"]] = did
        lines.append(json.dumps({"id": did, "type": "vertex", "label": "document",
                                 "uri": "file://" + f["path"],
                                 "languageId": f["language"] or "plaintext"}))
        lines.append(json.dumps({"id": nid(), "type": "edge", "label": "contains",
                                 "outV": proj, "inVs": [did]}))
    for s in con.execute("SELECT id, path, start_line, end_line, name FROM symbols"):
        did = docs.get(s["path"])
        if not did: continue
        rid = nid()
        lines.append(json.dumps({"id": rid, "type": "vertex", "label": "range",
                                 "start": {"line": s["start_line"] - 1, "character": 0},
                                 "end": {"line": s["end_line"] - 1, "character": 0}}))
        lines.append(json.dumps({"id": nid(), "type": "edge", "label": "contains",
                                 "outV": did, "inVs": [rid]}))
        rs = nid()
        lines.append(json.dumps({"id": rs, "type": "vertex", "label": "resultSet",
                                 "name": s["name"]}))
        lines.append(json.dumps({"id": nid(), "type": "edge", "label": "next",
                                 "outV": rid, "inV": rs}))
        lines.append(json.dumps({"id": nid(), "type": "edge", "label": "item", "outV": rs,
                                 "inVs": [rid], "document": did, "property": "definitions"}))
    return "\n".join(lines) + "\n"

def _markdown(con, root):
    from . import summarize
    repo = summarize.summary(root, None)
    m = summarize.map_(root)
    lines = ["# Architecture (generated by CIP v1.0)", "", repo.get("summary", ""), "",
             "## Subsystems", ""]
    for d in m["directories"][:25]:
        lines.append(f"- **{d['name']}** — {d['files']} files, {d['symbols']} symbols")
    hs = m.get("hotspots") or []
    if hs:
        lines += ["", "## Hotspots (recent change activity)", ""]
        lines += [f"- {h['path']} (score {h['score']})" for h in hs]
    lines += ["", "_Regenerate: `cip export --format markdown --out ARCHITECTURE.md`_"]
    return "\n".join(lines) + "\n"
