"""Intelligent file admission: WHAT to index and HOW MUCH intelligence to spend.
Truth priority: git ls-files > .gitignore parse > heuristics > config overrides."""
import os, re, subprocess
from .base import repo_root, load_config, DEFAULT_EXCLUDES

HARD_DIRS = DEFAULT_EXCLUDES
DOC_EXTS = {".md", ".mdx", ".rst", ".txt", ".adoc"}
CONFIG_EXTS = {".json", ".yaml", ".yml", ".toml", ".ini", ".dockerfile", ".properties"}
CONFIG_NAMES = {"dockerfile", "makefile", ".env", "justfile", "procfile", ".editorconfig"}
ASSET_EXTS = {".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".ico", ".woff", ".woff2",
              ".ttf", ".eot", ".mp3", ".mp4", ".mov", ".pdf", ".zip", ".gz", ".tar",
              ".wasm", ".bin", ".exe", ".dll", ".pyc", ".sqlite", ".db"}
LOCKFILES = {"package-lock.json", "yarn.lock", "pnpm-lock.yaml", "bun.lockb", "composer.lock",
             "cargo.lock", "poetry.lock", "gemfile.lock", "go.sum", "uv.lock", "flake.lock"}
GENERATED_RES = (re.compile(r"@generated"), re.compile(r"DO NOT EDIT", re.I),
                 re.compile(r"generated by", re.I), re.compile(r"auto-?generated", re.I))

# ---------- git as truth ----------

def git_tracked(root):
    """Gold standard: exactly the files git considers worth keeping."""
    try:
        out = subprocess.run(["git", "ls-files", "-z"], cwd=root, capture_output=True, timeout=60)
        if out.returncode == 0:
            return {p for p in out.stdout.decode("utf-8", "replace").split("\0") if p}
    except Exception:
        pass
    return None

def parse_gitignore(root):
    """Fallback: merge every .gitignore (nested included) into a matcher."""
    patterns = []
    for dirpath, dirnames, _ in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in HARD_DIRS]
        gi = os.path.join(dirpath, ".gitignore")
        if os.path.exists(gi):
            base = os.path.relpath(dirpath, root).replace(os.sep, "/")
            for line in open(gi, encoding="utf-8", errors="replace"):
                line = line.split("#", 1)[0].strip()
                if line and not line.startswith("!"):
                    patterns.append((base, line))
    return patterns

def _ignored(rel, patterns):
    for base, pat in patterns:
        p = pat.rstrip("/")
        full = p if base == "." else f"{base}/{p}"
        if (rel == full or rel.startswith(full + "/") or rel.endswith("/" + p)
                or ("/" + p + "/") in ("/" + rel + "/")):
            return True
    return False

# ---------- content heuristics ----------

def is_binary(ap):
    try:
        with open(ap, "rb") as f:
            return b"\x00" in f.read(8192)
    except OSError:
        return True

def is_minified(ap, size):
    if size > 2_000_000:
        return True
    try:
        with open(ap, encoding="utf-8", errors="replace") as f:
            head = f.read(4096)
        lines = head.splitlines() or [""]
        return len(head) > 2000 and (len(head) / len(lines)) > 200
    except OSError:
        return False

def is_generated(ap, rel):
    name = os.path.basename(rel).lower()
    if ".generated." in name or name.endswith((".min.js", ".min.css", ".bundle.js")):
        return True
    try:
        with open(ap, encoding="utf-8", errors="replace") as f:
            head = f.read(512)
        return any(rx.search(head) for rx in GENERATED_RES)
    except OSError:
        return False

def _looks_new_source(rel, ap):
    """Untracked-but-valid source: agents create files before committing them."""
    from .detect import lang_for
    if not lang_for(rel):
        return False
    try:
        with open(ap, encoding="utf-8", errors="replace") as f:
            head = f.read(512)
        return not any(rx.search(head) for rx in GENERATED_RES)
    except OSError:
        return False

# ---------- classification ----------

def classify(rel):
    """tier, reason — HOW MUCH intelligence to spend."""
    ext = os.path.splitext(rel)[1].lower()
    base = os.path.basename(rel).lower()
    if ext in ASSET_EXTS or base in LOCKFILES:
        return "skip", "asset/lockfile"
    if ext in DOC_EXTS or base == "readme":
        return "doc", "documentation"
    if ext in CONFIG_EXTS or base in CONFIG_NAMES:
        return "config", "config/infra"
    from .detect import lang_for
    if lang_for(rel):
        return "code", "source"
    return "pathonly", "unknown type"

def _decide(rel, ap, size, cfg, tracked, ign):
    include = cfg["index"].get("include", [])
    exclude = cfg["index"].get("exclude", [])
    maxb = int(cfg["index"]["max_file_kb"]) * 1024
    if any(m in rel for m in include):
        tier, _ = classify(rel)
        return "index", tier, "explicit include"
    if any(m in rel for m in exclude):
        return "skip", "-", "config exclude"
    if tracked is not None:
        if rel not in tracked and not _looks_new_source(rel, ap):
            return "skip", "-", "not tracked by git"
    elif ign is not None and _ignored(rel, ign):
        return "skip", "-", "gitignore"
    if is_binary(ap):
        return "skip", "-", "binary"
    tier, why = classify(rel)
    if tier == "skip":
        return "skip", "-", why
    if size > maxb:
        return "index", "pathonly", f"oversize ({size // 1024}KB)"
    if tier == "code" and is_generated(ap, rel):
        return "index", "pathonly", "generated code"
    if tier == "code" and is_minified(ap, size):
        return "index", "pathonly", "minified"
    return "index", tier, why

# ---------- public API ----------

def _scan(root):
    """Yield (rel_path, abs_path, size) for every regular file.

    Uses os.scandir so the size comes from the cached directory entry (no
    second stat syscall per file — a major speedup on Windows where stat is
    comparatively expensive)."""
    root = os.path.abspath(root)
    stack = [root]
    while stack:
        dirpath = stack.pop()
        try:
            with os.scandir(dirpath) as it:
                for e in it:
                    if e.is_dir(follow_symlinks=False):
                        if e.name not in HARD_DIRS:
                            stack.append(e.path)
                    elif e.is_file(follow_symlinks=False):
                        rel = os.path.relpath(e.path, root).replace(os.sep, "/")
                        try:
                            sz = e.stat(follow_symlinks=False).st_size
                        except OSError:
                            continue
                        yield (rel, e.path, sz)
        except OSError:
            continue

def iter_files_smart(root, cfg):
    """The intelligent front door. Yields (rel_path, tier, why) for indexable files."""
    tracked = git_tracked(root)
    ign = None if tracked is not None else parse_gitignore(root)
    for rel, ap, size in _scan(root):
        decision, tier, why = _decide(rel, ap, size, cfg, tracked, ign)
        if decision == "index":
            yield rel, tier, why

def admission_report(root=None):
    """Full audit of every decision — the trust/transparency feature."""
    root = root or repo_root(); cfg = load_config(root)
    tracked = git_tracked(root)
    ign = None if tracked is not None else parse_gitignore(root)
    tiers, skips = {}, {}
    examples = {}
    for rel, ap, size in _scan(root):
        d, tier, why = _decide(rel, ap, size, cfg, tracked, ign)
        key = tier if d == "index" else f"skip:{why}"
        if d == "index":
            tiers[key] = tiers.get(key, 0) + 1
            examples.setdefault(key, []).append(rel)
        else:
            skips[why] = skips.get(why, 0) + 1
    return {"mode": "git-tracked" if tracked is not None else "gitignore-fallback",
            "index_tiers": tiers, "skipped": skips,
            "examples": {k: v[:3] for k, v in examples.items()}}

def explain(root, rel):
    """Why was THIS file included/excluded? `cip admission --path src/x.ts`"""
    root = root or repo_root(); cfg = load_config(root)
    ap = os.path.join(root, rel)
    if not os.path.exists(ap):
        return f"{rel}: does not exist"
    try:
        size = os.path.getsize(ap)
    except OSError:
        return f"{rel}: unreadable"
    tracked = git_tracked(root)
    ign = None if tracked is not None else parse_gitignore(root)
    d, tier, why = _decide(rel, ap, size, cfg, tracked, ign)
    return f"{rel}: {d.upper()} as '{tier}' — {why}"

# ---------- doc chunking: headings are the 'symbols' of prose ----------

def chunk_markdown(path, source, cap=50):
    chunks, cur, start, title = [], [], 1, path
    lines = source.splitlines()
    def flush(end):
        text = "\n".join(cur).strip()
        if text:
            chunks.append({"id": f"{path}#L{start}-L{end}", "path": path,
                           "symbol_id": None, "start": start, "end": end,
                           "text": text[:8000]})
    for i, line in enumerate(lines):
        if re.match(r"^#{1,3} ", line) and cur:
            flush(i)
            cur, start, title = [], i + 1, line.lstrip("# ").strip()
        cur.append(line)
    flush(len(lines))
    return chunks[:cap]
